# Generated by Django 5.2.8 on 2025-11-30 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_product_catalog_pro_categor_7c1c1f_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='model_glb_url',
            field=models.URLField(blank=True),
        ),
    ]
