# Generated by Django 5.2.8 on 2025-11-30 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_product_model_glb_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sketchfab_embed_url',
            field=models.URLField(blank=True),
        ),
    ]
