# Generated by Django 5.2.8 on 2025-11-29 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_initial'),
        ('catalog', '0003_product_catalog_pro_categor_7c1c1f_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='cartitem',
            index=models.Index(fields=['cart'], name='cart_cartit_cart_id_4fb076_idx'),
        ),
        migrations.AddIndex(
            model_name='cartitem',
            index=models.Index(fields=['product'], name='cart_cartit_product_985dba_idx'),
        ),
    ]
