# Generated by Django 5.2.8 on 2025-11-30 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_options_user_users_user_role_36d76d_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='registration_number',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True),
        ),
    ]
