# Generated by Django 4.2.26 on 2025-12-07 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_registration_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModerationReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_id', models.CharField(max_length=64, unique=True)),
                ('type', models.CharField(max_length=128)),
                ('user_email', models.EmailField(blank=True, max_length=254)),
                ('submitted_by', models.EmailField(blank=True, max_length=254)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('under_review', 'Under Review'), ('resolved', 'Resolved'), ('rejected', 'Rejected')], default='pending', max_length=32)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['status'], name='users_moder_status_2bcabb_idx'), models.Index(fields=['severity'], name='users_moder_severit_e66c89_idx'), models.Index(fields=['created_at'], name='users_moder_created_f9971a_idx')],
            },
        ),
    ]
